### ISSUE TITLE
4x4 option

### ISSUE THREAD

**Issue by kevinmlewis** [TopoPhillMan/TicTackToe#4]
Instead of doing tic tac toe I want to do a connect 4 like options with the ability to switch between 3 and 4.

The code should handle both.  

We want to generalize the logic here.  So while tictactoe works we want to abstract our thought process and make it so that code is more generalized. 

I do like the option of breaking the program into classes.

**Comment by TopoPhillMan** [comment]
Should be resolved with pre-release v2.0.0-alpha 
https://github.com/TopoPhillMan/TicTackToe/releases/tag/v2.0.0
